workflows:
  android-workflow:
    name: Android Build
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.example.tvbrowser"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release --target-platform=android-arm,android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - tu_email@ejemplo.com
